enum UIEventCode {
	ENTER_ROOM,
	SET_LEFT_PLAYER_DATA,
	SET_RIGHT_PLAYER_DATA,
	PLAYER_ENTER,
	USER_LEAVE,
	PLAYER_LEAVE,
	PLAYER_READY,
	GAME_START,
	CHANGE_MULTIPLE,
	TURN_GRAB,
	GRAB_SUCCESS,
	PLAYER_CHANGE_IDENTITY,
	SET_TABLE_CARD,

	INIT_MY_CARD,
	INIT_LEFT_CARD,
	INIT_RIGHT_CARD,
	ADD_LEFT_CARD,
	ADD_RIGHT_CARD,
	ADD_MY_CARD,
	TURN_DEAL,
	DEAL_CARD,

	HIDE_DEAL_BUTTON,
	REMOVE_LEFT_CARD,
	REMOVE_RIGHT_CARD,
	REMOVE_MY_CARD,
	UPDATE_SHOW_DESK_CARDS,
	UPDATE_SHOW_DESK_PASS,

	UPDATE_OVER_PANEL
}